# Ripped from js

define t_ch_tutorial = NamcoChar(what_xalign=0.5, what_bold=True)

define t_ch_cousin = NamcoChar("[slot_playerName]", who_color="#FFF865", what_color="#FFF865")
define t_ch_davesprite = NamcoChar("Davesprite", who_color="#f2a400", what_color="#f2a400", screen="say_homestuck")
define t_ch_terezi = NamcoChar("Terezi", who_color="#008282", what_color="#008282", screen="say_homestuck")
define t_ch_jane = NamcoChar("Jane", who_color="#00d5f2", what_color="#00d5f2", screen="say_homestuck")

define t_ch_aki = NamcoChar("Aki")
define t_ch_albatros = NamcoChar("Al. B. Tross")
define t_ch_albatross = NamcoChar("Albatross")
define t_ch_antibravo = NamcoChar("Anti-Bravoman")
define t_ch_donko = NamcoChar("Donko")
define t_ch_galaga = NamcoChar("Galaga")
define t_ch_hiromi = NamcoChar("Hiromi")
define t_ch_lolo = NamcoChar("Lolo")
define t_ch_max = NamcoChar("Blue Max")
define t_ch_meowkie = NamcoChar("Meowkie")
define t_ch_mrdriller = NamcoChar("Mr. Driller")
define t_ch_nidia = NamcoChar("Nidia")
define t_ch_richard = NamcoChar("Richard Miller")
define t_ch_taira = NamcoChar("Taira")
define t_ch_toby = NamcoChar("Toby")
define t_ch_tomari = NamcoChar("Tomari")
define t_ch_valkyrie = NamcoChar("Valkyrie")
define t_ch_condor = NamcoChar("Condor")
define t_ch_condorconnie = NamcoChar("Condor I Mean Connie")
define t_ch_codenameconnie = NamcoChar("Codename Connie")
define t_ch_conniequestion = NamcoChar("Connie (...?)")
define t_ch_connie = NamcoChar("Connie")
define t_ch_pacman = NamcoChar("Pac-Man")
define t_ch_bullies = NamcoChar("bullies")
define t_ch_digdug = NamcoChar("Dig Dug")
define t_ch_pictures = NamcoChar("pictures")
define t_ch_dirtomari = NamcoChar("Director Tomari")
define t_ch_tomaribang = NamcoChar("Tomari!")
define t_ch_parents = NamcoChar("parents")
define t_ch_thunder = NamcoChar("thunder")
define t_ch_rain = NamcoChar("rain")
define t_ch_door = NamcoChar("door")
define t_ch_miller = NamcoChar("Miller")
define t_ch_amazona = NamcoChar("Amazona")
define t_ch_king = NamcoChar("King")
define t_ch_tairanokagekiyo = NamcoChar("Taira no Kagekiyo")
define t_ch_student = NamcoChar("Student")
define t_ch_student1 = NamcoChar("Student 1")
define t_ch_student2 = NamcoChar("Student 2")
define t_ch_student3 = NamcoChar("Student 3")
define t_ch_eating = NamcoChar("eating")
define t_ch_cousinmeowkie = NamcoChar("Cousin and Meowkie")
define t_ch_akiquestion = NamcoChar("Aki???")
define t_ch_nidiacousins = NamcoChar("Nidia & Cousin")
define t_ch_oven = NamcoChar("Oven")
define t_ch_coolguy = NamcoChar("A Cool Guy From Last Year")
define t_ch_robotprint = NamcoChar("Amazing Robot Blueprint")
define t_ch_shadowfigure = NamcoChar("Shadowy Figure")
define t_ch_darklord = NamcoChar("xx-d4rkl0rd99-xx")
define t_ch_unknown = NamcoChar("???")
define t_ch_questionmarks = NamcoChar("???")
define t_ch_mc = NamcoChar("M.C.")
define t_ch_waiter = NamcoChar("Waiter")
define t_ch_tarp = NamcoChar("Mysterious Tarp")
define t_ch_donkoandaki = NamcoChar("Donko and Aki")
define t_ch_referee = NamcoChar("Referee")  
define t_ch_cashier = NamcoChar("Cashier")
define t_ch_shadow1 = NamcoChar("Shadow 1")
define t_ch_shadow2 = NamcoChar("Shadow 2")
define t_ch_shadow3 = NamcoChar("Shadow 3")
define t_ch_announcer = NamcoChar("Announcer")
define t_ch_narrator = NamcoChar("Narrator")

# define scene = renpy.Store()

image i_sw_black = Solid("#000")
image i_sw_white = Solid("#FFF")