TextStore = {
    "t_ui_mainMenu": "Main Menu",
    "t_ui_returnToGame": "Return to Game",
    "t_ui_sound_vol": "Sound Volume",
    "t_ui_music_vol": "Music Volume",
    "t_ui_language": "Language",
    "t_ui_newGame": "New Game",
    "t_ui_continue": "Continue",
    "t_ui_store": "Store",
    "t_ui_options": "Options",
    "t_ui_credits": "Credits",
    "t_ui_done": "Done",
    "t_ui_done_bang": "Done!",
    "t_ui_dontjoin": "Don't Join a Club",
    "t_ui_areyousureclub": "Are you sure you don’t want to join a club?",
    "t_ui_notsureclub": "Wait: I wanted to look around some more…",
    "t_ui_sureclub": "Yeah: I’m not interested in any of these.",
    "t_ui_waitfordetention": "Wait for Detention to End.",
    "t_ui_areyousuretalk": "Are you sure you don’t want to talk to anyone else?",
    "t_ui_notsuretalk": "Wait: I wanted to talk to someone else…",
    "t_ui_suretalk1": "Yeah: I just want detention to be over with.",
    "t_ui_suretalk2": "Yeah: please just let this day be over.",
    "t_ui_suretalk3": "Yeah: I just want out of here.",
    "t_ui_bymyself1": "BY MYSELF.",
    "t_ui_bymyself2": "I HAVE TO DO THIS ON MY OWN.",
    "t_ui_yes": "Yes",
    "t_ui_no": "No",
    "t_ui_rusMain": "Return to Main Menu? All progress will be saved.",
    "t_ui_r2mainMenu": "Return to main menu",
    "t_ui_ruSure": "Are you sure?",
    "t_ui_cancel": "Cancel",
    "t_ui_nextday": "The next day ...",
    "t_ui_syncing": "Syncing user data",
    "t_ui_oops": "Oops!",
    "t_ui_errorLong": "We're sorry: but it looks like an error has occured. Please refresh your browser and try again.",
    "t_ui_refresh": "Refresh",
    "t_ui_notUnlocked": "You have not unlocked this character.",
    "t_ui_unlockNow": "Unlock Now",
    "t_ui_newgame": "Are you sure you want to start a new game?",
    "t_ui_nameCheck": "You are enrolling as ${slot:playerName}. Is that correct?",
    "t_ui_welcomeStudent": "Welcome to Namco High: ${slot:playerName}!",
    "t_ui_cousinDefault": "Cousin",
    "t_ui_nameError": "Your name must be between 2 and 18 letters long",
    "t_ui_tryAgainSmartbutt": "Try again, smartbutt",
    "t_com00.00": "Thank you students for saving me! I thought I was a goner!",
    "t_com01.00": "Thank: YOU: Pac-Man. We were only able to do it, because we were true to ourselves!"
}